### ISSUE TITLE
Add more CSS frameworks

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ubershmekel/cssbed#4]
Here is a good list: https://github.com/dbohdan/classless-css

**Comment by dohliam** [comment]
And here is another, slightly larger list :smile: 

https://github.com/dohliam/dropin-minimal-css

**Comment by dohliam** [comment]
@ubershmekel Thanks! I'm slowly adding the missing frameworks from your list (and the one that @EvgenyOrekhov posted above). It's hard to keep up with everything that comes out, so this is very helpful.

About Materialize CSS, you're right -- I just looked into this a bit further and it seems to be due to [this bug](https://github.com/Dogfalo/materialize/issues/6458) (feature?) in the framework. Looks like it might not fit the "minimal" use case after all, unfortunately. In any case, thanks for pointing this out!

**Comment by EvgenyOrekhov** [comment]
Closing this in favor of using https://dohliam.github.io/dropin-minimal-css/.
